//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOrderLine
    {
        public long orderLineId { get; set; }
        public long orderId { get; set; }
        public long productId { get; set; }
        public int quantity { get; set; }
        public double price { get; set; }
    
        public virtual ClientOrder ClientOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
