//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientOrder()
        {
            this.ClientOrderLine = new HashSet<ClientOrderLine>();
        }
    
        public long orderId { get; set; }
        public System.DateTime orderDate { get; set; }
        public string orderName { get; set; }
        public Nullable<long> creditCardId { get; set; }
        public string clientOrderAddress { get; set; }
        public Nullable<long> clientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual CreditCard CreditCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOrderLine> ClientOrderLine { get; set; }
    }
}
