//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComment
    {
        public long commentId { get; set; }
        public long productId { get; set; }
        public string commentText { get; set; }
        public System.DateTime commentDate { get; set; }
        public long clientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }

        public virtual List<Tag> Tags { get; set; }
    }
}
