//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {

        public Tag(String tagName)
        {
            this.tagName = tagName;
        }

        public long tagId { get; set; }
        public string tagName { get; set; }
    }
}
