//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMad.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Es.Udc.DotNet.PracticaMad.Model.Services.ProductService.IProductService")]
        public string ObjectDS_Product_Service {
            get {
                return ((string)(this["ObjectDS_Product_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FindProductByProductNameKeyword")]
        public string ObjectDS_Product_SelectMethod {
            get {
                return ((string)(this["ObjectDS_Product_SelectMethod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CountProductByProductNameKeyword")]
        public string ObjectDS_Product_CountMethod {
            get {
                return ((string)(this["ObjectDS_Product_CountMethod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("startIndex")]
        public string ObjectDS_Product_StartIndexParameter {
            get {
                return ((string)(this["ObjectDS_Product_StartIndexParameter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("count")]
        public string ObjectDS_Product_CountParameter {
            get {
                return ((string)(this["ObjectDS_Product_CountParameter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int PracticaMad_defaultCount {
            get {
                return ((int)(this["PracticaMad_defaultCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetNumberOfOrdersByClient")]
        public string ObjectDS_OwnOrders_CountMethod {
            get {
                return ((string)(this["ObjectDS_OwnOrders_CountMethod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("startIndex")]
        public string ObjectDS_OwnOrders_StartIndexParameter {
            get {
                return ((string)(this["ObjectDS_OwnOrders_StartIndexParameter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("count")]
        public string ObjectDS_OwnOrders_CountParameter {
            get {
                return ((string)(this["ObjectDS_OwnOrders_CountParameter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetClientOrders")]
        public string ObjectDS_OwnOrders_SelectMethod {
            get {
                return ((string)(this["ObjectDS_OwnOrders_SelectMethod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Es.Udc.DotNet.PracticaMad.Model.Services.ProductService.IClientOrderService")]
        public string ObjectDS_OwnOrders_Service {
            get {
                return ((string)(this["ObjectDS_OwnOrders_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/PracticaMad")]
        public string PracticaMad_applicationURL {
            get {
                return ((string)(this["PracticaMad_applicationURL"]));
            }
        }
    }
}
